version: '3.7'

services:
  zk1:
    hostname: zk1
    image: confluentinc/cp-zookeeper:7.5.2
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_SERVERS: 0.0.0.0:2888:3888,zk2:2888:3888
    ports:
      - 22181:2181
      - 8081:8080
    # kafka does not like windows based filesystem mounts 
    #volumes:
    #  - ~/zookeeper/data1:/var/lib/zookeeper/data
    #  - ~/zookeeper/logs1:/var/lib/zookeeper/log
    networks:
      priv-kafka-net:
 
  zk2:
    hostname: zk2
    restart: always
    image: confluentinc/cp-zookeeper:7.5.2
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_SERVERS: zk1:2888:3888,0.0.0.0:2888:3888
    ports:
      - 22182:2181
      - 8082:8080
    # kafka does not like windows based filesystem mounts 
    #volumes:
    #  - ~/zookeeper/data2:/var/lib/zookeeper/data
    #  - ~/zookeeper/logs2:/var/lib/zookeeper/log
    networks:
      priv-kafka-net:
 
  zoonavigator:
    container_name: zoonav
    image: elkozmon/zoonavigator
    ports:
      - 9000:9000
    networks:
      priv-kafka-net:

  kaf1:
    hostname: kaf1
    restart: always
    image: confluentinc/cp-kafka:7.5.2
    depends_on:
      - zk1
      - zk2
    ports:
      - "29092:9092"
      - "29093:9093"
    # kafka does not like windows based filesystem mounts 
    #volumes:
    #  - ~/kafka/data1:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kaf1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2182/kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kaf1:9092, PLAINTEXT_HOST://kaf1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_INSYNC_REPLICAS: 2
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MA: 300000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 6000
    networks:
      priv-kafka-net:

  kaf2:
    hostname: kaf2
    restart: always
    image: confluentinc/cp-kafka:7.5.2
    depends_on:
      - zk1
      - zk2
    ports:
      - "29094:9092"
      - "29095:9093"
    # kafka does not like windows based filesystem mounts 
    #volumes:
    #  - ~/kafka/data2:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: kaf2
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2182/kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kaf2:9094, PLAINTEXT_HOST://kaf2:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_INSYNC_REPLICAS: 2
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MA: 300000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 6000
    networks:
      priv-kafka-net:

  kaf3:
    hostname: kaf3
    restart: always
    image: confluentinc/cp-kafka:7.5.2
    depends_on:
      - zk1
      - zk2
    ports:
      - "29096:9092"
      - "29097:9093"
    # kafka does not like windows based filesystem mounts 
    #volumes:
    #  - ~/kafka/data3:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: kaf3
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2182/kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kaf3:9096, PLAINTEXT_HOST://kaf3:9097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_INSYNC_REPLICAS: 2
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MA: 300000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 6000
    networks:
      priv-kafka-net:

networks:
  priv-kafka-net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.3.0/28